/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common.utils;

/**
 *
 * @author johny
 */
public enum MessageType {
    // -- Message Codes --
    // Network Connection Messages

    UNKNOWN_HOST_EXCEPTION,
    IO_EXCEPTION,
    NO_CONNECTION_BROADCAST,
    // Signup
    SIGNUP_REQUEST,
    ACCOUNT_ID,
    USERNAME_UNAVAILABLE,
    // Change User Profile
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_SUCCESS,
    DELETE_ACCOUNT_REQUEST,
    DELETE_ACCOUNT_SUCCESS,
    // Login
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    // User Sessions
    NEW_USER_SESSION_REQUEST, // USER TO SERVER
    NEW_USER_SESSION, // SERVER TO USER
    NEW_USER_SESSION_ACK, // USER TO SERVER

    // Logout
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    // Search for User for ACR
    SEARCH_FOR_USER_REQUEST,
    SEARCH_FOR_USER_RESPONSE,
    // Add Contact Request
    ADD_CONTACT_REQUEST, // QUESTER -> SERVER
    ADD_CONTACT_REQ_ACK, // SERVER -> QUESTER
    ACR_DELIVERY, // SERVER -> RECIPIENT
    ACR_DELIVERY_ACK, // RECIPIENT -> SERVER
    ACR_DECISION, // RECIPIENT -> SERVER
    ACR_DECISION_ACK, // SERVER -> RECIPIENT
    ACR_DECISION_DELIVERY, // SERVER -> QUESTER
    ACR_DECISION_DELIVERY_ACK, // QUESTER -> SERVER
    // Populate Notifications
    MISSED_ACRS, // AT LOGIN 
    MISSED_ACR_DECISIONS, // AT LOGIN 
    MISSED_CALLS, // AT LOGIN
    MISSED_CHATS, // AT LOGIN
    MISSED_FILES,
    // Conversations
    NEW_CONVERSATION_REQ, // USER -> SERVER
    NEW_CONVERSATION_DELIVERY, // SERVER -> PARTICIPANTS
    USER_JOINED_CONVERSATION, // USER -> SERVER
    PARTICIPANT_JOINED_CONVERSATION, // SERVER -> PARTICIPANTS
    USER_LEFT_CONVERSATION, // USER -> SERVER
    PARTICIPANT_LEFT_CONVERSATION, // SERVER -> PARTICIPANTS
    CONVERSATION_END, // SERVER -> LAST PARTICIPANT

    // Chat Messages
    CHAT_MSG_SEND_REQ, // SENDER TO SERVER
    CHAT_MSG_DELIVERY, // SERVER TO RECIPIENTs
    CHAT_MSG_DELIVERY_ACK, // RECIPIENT TO SERVER
    CHAT_MSG_DELIVERY_REPORT, // SENT BY SERVER TO SENDER
    CHAT_MSG_DELIVERY_REPORT_ACK, // SENT BY SENDER TO SERVER

    // File Transfers
    FILE_SEND_REQ, // SENDER TO SERVER
    FILE_SEND_ACK, // SERVER TO SENDER
    FILE_SEND_SERVER_REJECTION, // SERVER TO SENDER
    FILE_UPLOAD_COMPLETED,
    FILE_NOTIFICATION, // SERVER TO RECIPIENT
    FILE_NOTIFICATION_ACK, // RECIPIENT TO SERVER
    FILE_DOWNLOAD_COMPLETED,
    FILE_DOWNLOAD_REPORT, // SENT BY SERVER TO SENDER
    FILE_DOWNLOAD_REPORT_ACK, // SENT BY SENDER TO SERVER

    // Contact updates
    CONTACT_ADDITION, // SERVER TO USER
    CONTACT_ADDED_ACK, // USER TO SERVER
    USER_UPDATE, // USER TO SERVER 
    USER_ICON_UPDATE,
    CONTACT_UPDATE, // SERVER TO CONTACTS - NO NEED FOR ACK (CONTACT MAY BE OFFLINE)
    CONTACT_ICON_UPDATE,
    CONTACT_DELETION, // USER TO SERVER
    CONTACT_BROKEN, // SERVER TO CONTACT
    CONTACT_BROKEN_ACK, // CONTACT TO SERVER - NEED THIS TO UPDATE DB

    // App Version meta
    NEWEST_VERSION_REQUEST,
    NEWEST_VERSION_RESPONSE,
    // Termination of communication
    COMMUNICATION_TERMINATION_REQUEST, // USED BY APP TO TERMINATE CONNECTION SMOOTHLY
    COMMUNICATION_TERMINATION_RESPONSE, // USED BY APP TO TERMINATE CONNECTION SMOOTHLY

}
